config/routes.rb
Rails.application.routes.draw do

  root                       'static_pages#home'
  get    'help'           => 'static_pages#help'
  get    'about'          => 'static_pages#about'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  get    'auth/:provider/callback', to: 'sessions#facebook_oauth'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :locations

  resources :categories do
    resources :posts, except: [:index], controller: 'categories/posts'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:index] do
    resources :postattachments
    resources :reviews, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @posts = Post.where("posts.created_at > ?", 10.days.ago).paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About</h1>
<h2>
  Pets home is the great place to seek help from pets' lovers! 
</h2>

app/views/static_pages/contact.html.erb
<div class="container">
<h1>Contact</h1>
<p>
  You can email us to support@pethome.co
</p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<div class="container">
<h1>Help</h1>
<p>
  Any questions? Pleasse email to admin@pethome.co
</p>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <%= render :template => 'posts/index' %>
<% else %>
  <div id="bg-fade-carousel" class="carousel slide carousel-fade" data-ride="carousel">
  <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <div class="slide1"></div>
      </div>
      <div class="item">
        <div class="slide2"></div>
      </div>
      <div class="item">
        <div class="slide3"></div>
      </div>
      <div class="item">
        <div class="slide4"></div>
      </div>
      <div class="item">
        <div class="slide5"></div>
      </div>
      <div class="item">
        <div class="slide6"></div>
      </div>
      <div class="item">
        <div class="slide7"></div>
      </div>
      <div class="item">
        <div class="slide8"></div>
      </div>
    </div><!-- .carousel-inner --> 
    <div class="container carousel-overlay text-center">
      <div class="col-md-12">
      <h1>Welcome to Pet Home</h1>
      <h2>Connect with other pet lovers fast and easy</h2>
      <h2>
        <%= link_to "Log in", login_path, class: "btn btn-warning btn-lg" %> 
        or 
        <%= link_to "Sign up", signup_path, class: "btn btn-warning btn-lg" %>
      </h2>
      </div>
    </div>
    <a class="left carousel-control" href="#bg-fade-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </a>
    <a class="right carousel-control" href="#bg-fade-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    </a>
  </div><!-- .carousel --> 
<% end %>