config/routes.rb
Rails.application.routes.draw do

  root                       'static_pages#home'
  get    'help'           => 'static_pages#help'
  get    'about'          => 'static_pages#about'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  get    'auth/:provider/callback', to: 'sessions#facebook_oauth'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :locations

  resources :categories do
    resources :posts, except: [:index], controller: 'categories/posts'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:index] do
    resources :postattachments
    resources :reviews, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save   :downcase_email
  before_create :create_activation_digest
  has_many :posts, dependent: :destroy
  has_many :locations, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 250 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false}
  has_secure_password
  
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
                                
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost:cost)                                               
  end    

  def User.new_token
    SecureRandom.urlsafe_base64
  end   

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end     

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end  

  def forget
    update_attribute(:remember_digest, nil)
  end  

  def activate 
    update_columns(activated: true, activated_at: Time.zone.now)
  end  

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  def create_reset_digest
    self.reset_token = User.new_token
    update_columns(reset_digest:  User.digest(reset_token),
                   reset_sent_at: Time.zone.now)
  end

  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first

    if user
      return user
    else
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.name = auth.info.name unless user.name != nil
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email unless user.email != nil
        user.image = auth.info.image unless user.image != nil
        user.activated = true
        user.password = SecureRandom.urlsafe_base64 unless user.password != nil
        user.save!
      end
    end
  end

  private

    def downcase_email
      self.email = email.downcase
    end

    def create_activation_digest
      self.activation_token = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.friendly.find(params[:id])
    @posts = @user.posts
    @reviews = @user.reviews
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_activation_email
      flash[:info] = "Thanks for signing up! Please check your email to activate 
                      your account."
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.friendly.find(params[:id])
  end

  def update
    @user = User.friendly.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.friendly.find(params[:id]).destroy
    flash[:success] ="User deleted"
    redirect_to users_url
  end

  private 

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmtaion, :description, :phone_number)
    end

    def correct_user
      @user = User.friendly.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 164 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    if user.image
      user.image
    else
      "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    end
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', object: f.object %>

<div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <em>(6 characters minimum)</em>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, "Password Confirmation" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <% if logged_in? %>
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: "form-control", placeholder: "Phone Number" %>

    <%= f.label :description %>
    <%= f.text_area :description, rows: 5, cols: 25, class: "form-control", placeholder: "Tell us about yourself" %>
  <% end %>
</div>

app/views/users/_user.html.erb
 <li>
  <%= image_tag gravatar_url(user), class: "avatar-medium"%>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?"} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<div class="container">
  <% provide(:title, "Edit user") %>
  <h1>Update your setting</h1>

  <div class="row">
    <div class="col-md-4">
      <div class="row">
        <%= image_tag gravatar_url(@user), class: "gravatar" %>
      </div>

      <div class="row-space-1">
        <% unless @user.image %>
          <a href="http://gravatar.com/emails" target="_blank">Change your picture</a>
        <% end %>
      </div>
    </div>
    <div class="col-md-8">
      <%= form_for(@user) do |f| %>
        <%= render 'fields', f: f %>
        
        <div class="form-group">
          <%= f.submit "Save changes", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<div class="container">
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<div class="container">
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'fields', f: f %>
      </br>
      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="container">
  <div class = "row">
    <aside class="col-md-3">
      <section class="user_info">
        <h1>
          <%= image_tag gravatar_url(@user), class: "avatar-full" %>
        </h1>
      </section>
      <% if current_user != @user %>
        <div class="row-space-2">
          <%= link_to "Send Message", conversations_path(sender_id: current_user.id, recipient_id: @user.id), method: 'post', class: "btn btn-warning wide" %>
        </div>
      <% end %>
      Phone Number<br>
      Email Address
    </aside>
    <div class="col-md-9">
      <h2><%= @user.name %></h2>

      <div class="descritption row-space-3">
        <%= @user.description %>
      </div>
    </div>
  </div>

  <div class = "row-space-3">
    <small>
      <%= pluralize(@user.posts.count, 'post') %>
      <div class="js-userreviews-count"><%= pluralize(@user.reviews.count, 'review') %></div>
    </small>

    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#posts" data-toggle="tab">Posts</a></li>
        <li><a href="#reviews" data-toggle="tab">Reviews</a></li>
      </ul>
      <div class="tab-content">
        <br>
        <div class="tab-pane active" id="posts">
          <%= render @posts %>
        </div>
        <div class="tab-pane" id="reviews">
          <% @user.reviews.each do |review| %>
            <%= render 'reviews/review', review: review, show_post: true %>
          <% end %>
        </div>
      </div>
  </div>
  </div>
</div>