config/routes.rb
Rails.application.routes.draw do

  root                       'static_pages#home'
  get    'help'           => 'static_pages#help'
  get    'about'          => 'static_pages#about'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  get    'auth/:provider/callback', to: 'sessions#facebook_oauth'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :locations

  resources :categories do
    resources :posts, except: [:index], controller: 'categories/posts'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:index] do
    resources :postattachments
    resources :reviews, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  searchkick
  belongs_to :user
  belongs_to :category

  belongs_to :location, dependent: :destroy
  accepts_nested_attributes_for :location, allow_destroy: true              
                                  
  has_many :postattachments, dependent: :destroy
  has_many :reviews, dependent: :destroy

  default_scope { order('created_at DESC') }


  validates :user_id, presence: true
  validates :title, length: { minimum: 5}, presence: true
  validates :body, length: { minimum: 20 }, presence: true


end

app/controllers/categories/posts_controller.rb
class Categories::PostsController < ApplicationController
  before_action :set_category
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :authorize_user, only: [:edit, :update, :destroy]
  
  def show
    @postattachments = @post.postattachments
  end

  def new    
    @post = Post.new
    # if current_user.locations.first
    #   @post.locations = current_user.locations.first
    # else
      @post.build_location
    # end

  end

  def create   

    @post = current_user.posts.build(post_params)
    @post.category = @category

    if @post.save
      if params[:pictures]
        params[:pictures].each do |picture|
          @post.postattachments.create(picture: picture)
        end
      end
      
      @postattachments = @post.postattachments
      flash[:success] = "You have succesfully created a new post."
      redirect_to edit_category_post_path(@category, @post)
    else
      flash[:danger] = "Error occured. Please try again."
      render :new
    end
  end


  def edit 
    @postattachments = @post.postattachments

    if @post.location.blank?
    
      # if current_user.locations.first
      #   @post.location = current_user.locations.first 
      # else
        @post.build_location
    end
  end

  def update    
    if @post.update_attributes(post_params)
      if params[:pictures]
        params[:pictures].each do |picture|
          @post.postattachments.create(picture: picture)
        end
      end
      flash[:success] = "Post was upated."
      redirect_to edit_category_post_path(@category, @post)
    else
      flash[:danger] = "There was an error saving a post, please try again."
      render :new
    end
  end

  def destroy
    title = @post.title

      if @post.destroy
        flash[:success] = "\"#{title}\" was deleted successfully."
        redirect_to @category
      else
        flash[:danger] = "There was an error deleting the topic."
        render :show
      end
  end

  private 

    def set_category
      @category = Category.friendly.find(params[:category_id])
    end

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, location_attributes: [:id, :street, :city, :zipcode, :state, :_destroy])
    end

    def authorize_user
      unless (current_user.admin? || @post.user == current_user)
        flash[:danger] = "You don't have permission to delete this post." 
        redirect_to root_url 
      end
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    if logged_in?
      @posts = Post.where("posts.created_at > ?", 10.days.ago).paginate(page: params[:page])
    else
      @posts = Post.all.paginate(page: params[:page])
    end
  end

  def search
    @posts = Post.search(params[:search], page: params[:page], per_page: 20)
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
  def user_is_authorized_for_post?(post)
    current_user && (current_user == post.user) || current_user.admin?
  end
end

app/views/posts/_post.html.erb
<div class="media">
  <div class="media-body">
    <div class="col-md-2">
      <%= image_tag post.postattachments[0].picture.url(:thumb) if post.postattachments.length > 0 %>
    </div>
    <div class="col-md-10">
    <h4 class="media-heading">
      <%= link_to post.title, [post.category, post] %>
    </h4>
    <small>
      submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br/>
    </small>
        
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% if logged_in? %>
        <h1>Recent Posts</h1>
        <p class="lead">Active posts in the past 10 days</p>
        <%= will_paginate @posts %>
        <%= render @posts %>
        <%= will_paginate @posts %>
      <% else %>
        <h1>All Posts</h1>

        <%= will_paginate @posts %>
        <%= render @posts %>
        <%= will_paginate @posts %>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<div class="container">
<div class="row">
  <div class="col-md-12">
  
    <h1>Search</h1>
      <div class="form-group">
        <%= form_tag search_posts_path, method: :get do %>
        <div class="col-md-8">
        <%= text_field_tag :search, params[:search], class: "form-control",placeholder: 'Search for..' %>
        </div>
        <%= submit_tag "Find", name: nil, class: "btn btn-default" %>
        <% end %>
      </div>
  </div>
    <%= render @posts %>
    <%= will_paginate @posts %>
</div>
</div>