config/routes.rb
Rails.application.routes.draw do

  root                       'static_pages#home'
  get    'help'           => 'static_pages#help'
  get    'about'          => 'static_pages#about'
  get    'contact'        => 'static_pages#contact'
  get    'signup'         => 'users#new'
  get    'login'          => 'sessions#new'
  post   'login'          => 'sessions#create'
  delete 'logout'         => 'sessions#destroy'
  get    'auth/:provider/callback', to: 'sessions#facebook_oauth'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :locations

  resources :categories do
    resources :posts, except: [:index], controller: 'categories/posts'
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create, :destroy]
  end

  resources :posts, only: [:index] do
    resources :postattachments
    resources :reviews, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :posts, dependent: :destroy
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/categories/posts_controller.rb
class Categories::PostsController < ApplicationController
  before_action :set_category
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user
  before_action :authorize_user, only: [:edit, :update, :destroy]
  
  def show
    @postattachments = @post.postattachments
  end

  def new    
    @post = Post.new
    # if current_user.locations.first
    #   @post.locations = current_user.locations.first
    # else
      @post.build_location
    # end

  end

  def create   

    @post = current_user.posts.build(post_params)
    @post.category = @category

    if @post.save
      if params[:pictures]
        params[:pictures].each do |picture|
          @post.postattachments.create(picture: picture)
        end
      end
      
      @postattachments = @post.postattachments
      flash[:success] = "You have succesfully created a new post."
      redirect_to edit_category_post_path(@category, @post)
    else
      flash[:danger] = "Error occured. Please try again."
      render :new
    end
  end


  def edit 
    @postattachments = @post.postattachments

    if @post.location.blank?
    
      # if current_user.locations.first
      #   @post.location = current_user.locations.first 
      # else
        @post.build_location
    end
  end

  def update    
    if @post.update_attributes(post_params)
      if params[:pictures]
        params[:pictures].each do |picture|
          @post.postattachments.create(picture: picture)
        end
      end
      flash[:success] = "Post was upated."
      redirect_to edit_category_post_path(@category, @post)
    else
      flash[:danger] = "There was an error saving a post, please try again."
      render :new
    end
  end

  def destroy
    title = @post.title

      if @post.destroy
        flash[:success] = "\"#{title}\" was deleted successfully."
        redirect_to @category
      else
        flash[:danger] = "There was an error deleting the topic."
        render :show
      end
  end

  private 

    def set_category
      @category = Category.friendly.find(params[:category_id])
    end

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body, location_attributes: [:id, :street, :city, :zipcode, :state, :_destroy])
    end

    def authorize_user
      unless (current_user.admin? || @post.user == current_user)
        flash[:danger] = "You don't have permission to delete this post." 
        redirect_to root_url 
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_category
  before_action :set_category, except: [:index, :new, :create]
  before_action :logged_in_user, except: [:show]
  before_action :admin_user,     except: [:show]
  
  def index
    @categories = Category.all
  end

  def show
    @posts = @category.posts.paginate(page: params[:page])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:success] = "Category has been created!"
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes(category_params)
      flash[:success] = "Category updated"
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def destroy
    name = @category.name

    if @category.destroy
      flash[:success] = "\"#{name}\" was deleted successfully."
      redirect_to root_url
    else
      flash[:error] = "There was an error deleting the category."
      render :show
    end
  end

  private 

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end


  def admin_user
    redirect_to(root_url) unless current_user.admin?
    end

  def invalid_category
    logger.error "Attempt to access invalid category #{params[:id]}"
    flash[:danger] = "Invalid category"
    redirect_to root_url
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<% provide(:title, 'Create a new category') %>
<div class="container">
  <div class="well">
    <%= form_for @category do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, rows: 2, class: 'form-control' %>
    </div> 

    </br> 
      <%= f.submit "Edit category", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/categories/index.html.erb
<h1> All Categories </h1>

<div class="container">
<table class="table  table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Delete', category, method: :delete, data: { confirm: 'Are you sure? Once it is deleted, all the related posts will be all gone!' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</br>

<%= link_to "New Category", new_category_path %>
</div>

app/views/categories/new.html.erb
<% provide(:title, 'Create a new category') %>
<div class="container">
  <div class="well">
    <%= form_for @category do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    </div> 

    </br> 
      <%= f.submit "Create new category", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container">
<h1><%= @category.name %></h1>
<h2><%= @category.description%></h2>

<div class="row">
  <div class="col-md-10">
    <%= will_paginate @posts %>
    <%= render @posts %>
    <%= will_paginate @posts %>
  </div>
  <div class="col-md-2">
    <%= link_to "New Post for #{@category.name}", new_category_post_path(@category), class: 'btn btn-warning pull-right' %>
  </div>
</div>
</div>